name: ng_fontawesome_demo
description: Demo for ng_fontawesome
authors:
  - Mark E. Haase <mehaase@gmail.com>
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  ng_fontawesome: any
dependency_overrides:
  ng_fontawesome:
    path: ../ng_fontawesome
dev_dependencies:
  build_runner: ^1.8.0
  build_test: ^0.10.12+1
  build_web_compilers: ^2.9.0
